const lang = {
  'Login.Title': '登录到 Telegram',
  'Login.PhoneLabel': '手机号码',
  'Login.PhoneLabelInvalid': '手机号码无效',
  'Login.StartText': '请确认您的国家代码\n并输入您的手机号码。',
  'Login.Code.SentSms': '我们已向您发送了一条短信\n其中包含验证码。',
  'Login.Code.SentInApp': '我们已在 Telegram 中向您发送了一条消息\n其中包含验证码。',
  'Login.Code.SentCall': '我们将致电您并口述\n验证码。',
  'Login.Code.SentEmail': '请检查您的邮箱 **%s**（不要忘记垃圾邮件文件夹）并输入我们刚刚发送给您的验证码。',
  'Login.Code.SentUnknown': '请检查所有位置\n查找验证码（类型：%s）',
  'Login.Password.Title': '输入您的密码',
  'Login.Password.Subtitle': '您的帐户受到\n额外密码保护',
  'Login.Register.Subtitle': '输入您的姓名并添加\n个人资料照片',
  'PleaseWait': '请稍候...',

  'ForgotPassword': '[忘记密码？]()',
  'TroubleEmail': '[无法访问此邮箱？]()',
  'Login.ResetPassword.Title': '重置密码',
  'Login.ResetPassword.Subtitle': '输入我们刚刚发送到\n您的邮箱 **%s** 的验证码。',
  'Login.ResetPassword.Cancel': '取消',
  'Login.ResetPassword.NoEmailText': '由于您在设置密码时没有提供恢复邮箱，因此您剩下的选择是记住密码或重置帐户。',
  'Login.ResetPassword.TroubleEmailText': '如果您无法恢复对邮箱的访问，剩下的选择是记住密码或重置帐户。',
  'Login.ResetPassword.ResetAccount': '重置帐户',
  'Login.ResetAccount.Title': '警告',
  'Login.ResetAccount.Text': '此操作无法撤消。\n\n如果您重置帐户，所有消息和聊天都将被删除。',
  'Login.ResetAccountFail.Title': '抱歉',
  'Login.ResetAccountFail.TextCancelled': '您最近重置此帐户的尝试已被其活跃用户取消。请在 7 天后重试。',
  'Login.ResetAccountFail.TextWait': '由于此帐户处于活动状态并受密码保护，出于安全考虑，我们将在 1 周后删除它。\n\n您可以随时取消此过程。\n\n您将能够在以下时间后重置帐户：%s。',
  'Login.ResetEmail.Title': '重置邮箱',
  'Login.ResetEmail.Text': '如果您已从另一台设备登录 Telegram，则可以更改登录邮箱。\n\n否则，如果您无法访问此邮箱，可以在 **%s** 内使用 **短信** 验证码重置它。',
  'Login.ResetEmail.Pending': '邮箱将在 %s 后重置。[立即通过短信重置]()',
  'Login.ResetEmail.PleaseWait': '正在重置邮箱，请稍候...',
  'Login.ResetEmail.NeedPremium': '需要 Telegram Premium',
  'Login.ResetEmail.NeedPremiumText': '由于您所在国家/地区的短信费用较高，您需要 **Telegram Premium** 帐户才能通过短信验证码立即重置此邮箱。\n\n您可以请朋友为您的帐户赠送 Premium 订阅',
  'Login.Passkey': '使用通行密钥登录',
  'Login.Passkey.Error': '出了点问题',
  'Login.Passkey.Error.NotFound': '使用的通行密钥未绑定到任何帐户',

  // * android
  'Code': '验证码',
  'LoginPassword': '密码',
  'YourName': '您的姓名',
  'FirstName': '名字（必填）',
  'LastName': '姓氏（可选）',
  'StartMessaging': '开始聊天',
  'Country': '国家',

  // * macos
  'Contacts.PhoneNumber.Placeholder': '手机号码',
  'Login.Next': '下一步',
  'Login.ContinueOnLanguage': '继续使用中文',
  'Login.QR.Title': '通过二维码登录 Telegram',
  'Login.QR.Help1': '在手机上打开 Telegram',
  'Login.QR.Help2': '前往 **设置** > **设备** > **关联桌面设备**',
  'Login.QR.Help3': '将手机对准此屏幕以确认登录',
  'Login.QR.Cancel': '使用手机号码登录',
  'Login.QR.Login': '使用二维码登录',
  'PhoneNumber.Code.Fragment.Info': '在 [Fragment](%1$@) 的匿名号码部分获取验证码',
  'PHONE_CODE_INVALID': '验证码无效',
  'PHONE_CODE_EXPIRED': '验证码已过期',
  'PASSWORD_HASH_INVALID': '密码错误'
};

export default lang;
