const lang = {
  'Animations': '动画',
  'AttachAlbum': '相册',
  'Appearance.Color.Hex': '十六进制',
  'Appearance.Color.RGB': 'RGB',
  'BlockModal.Search.Placeholder': '屏蔽用户...',
  'DarkMode': '深色模式',
  'FilterIncludeExcludeInfo': '选择将在此文件夹中显示和永不显示的聊天和聊天类型。',
  'FilterMenuDelete': '删除文件夹',
  'FilterHeaderEdit': '编辑文件夹',
  'FilterAllGroups': '所有群组',
  'FilterAllContacts': '所有联系人',
  'FilterAllNonContacts': '所有非联系人',
  'FilterAllChannels': '所有频道',
  'FilterAllBots': '所有机器人',
  'FilterPersonal': '个人',
  'EditContact.OriginalName': '原始名称',
  'EditProfile.FirstNameLabel': '名字',
  'EditProfile.BioLabel': '个人简介（可选）',
  'EditProfile.Username.Label': '用户名（可选）',
  'EditProfile.Username.Available': '用户名可用',
  'EditProfile.Username.Taken': '用户名已被占用',
  'EditProfile.Username.Invalid': '用户名无效',
  'EditFolder.Toast.ChooseChat': '请为此文件夹至少选择一个聊天。',
  'EditFolder.EmojiAsIconTip': '如果您在开头（或结尾）只放一个表情符号，它将显示为文件夹侧边栏中的图标',
  'EditProfile.AddBirthdayRow': '添加生日',
  'EditBot.Title': '编辑机器人',
  'EditBot.Username.Caption': '此用户名无法编辑。',
  'EditBot.Buttons.Caption': '使用 [@BotFather](https://t.me/botfather) 来管理此机器人。',
  'EditBot.Buttons.Intro': '编辑介绍',
  'EditBot.Buttons.Commands': '编辑命令',
  'EditBot.Buttons.Settings': '更改机器人设置',
  'ExceptionModal.Search.Placeholder': '添加例外...',
  'Chat.Menu.SelectMessages': '选择消息',
  'Chat.Menu.ClearSelection': '清除选择',
  'Chat.Menu.Hint': '要**编辑**或**回复**，请关闭此菜单。\n然后点击消息旁边。',
  'Chat.Menu.SendGift': '发送礼物',
  'Chat.Input.UnpinAll': '取消固定所有消息',
  'Chat.Input.Attach.PhotoOrVideo': '照片或视频',
  'Chat.Input.Attach.Document': '文档',
  'Chat.Subscribe': '订阅',
  'Chat.Selection.LimitToast': '已达到最大选择数量。',
  'Chat.Search.MessagesFound': {
    'one_value': '找到 %d 条消息',
    'other_value': '找到 %d 条消息'
  },
  'Chat.Search.NoMessagesFound': '未找到消息',
  'Chat.Search.PrivateSearch': '私密搜索',
  'ChatsNew': {
    'one_value': '%d 个新聊天',
    'other_value': '%d 个新聊天'
  },
  'ChatList.Main.EmptyPlaceholder.Title': '您的聊天将在此显示',
  'ChatList.Main.EmptyPlaceholder.Subtitle': '您在 Telegram 上有 %s',
  'ChatList.Main.EmptyPlaceholder.SubtitleNoContacts': '使用 [Android](https://telegram.org/android) 或 [iOS](https://telegram.org/dl/ios) 设备上的 Telegram 应用同步您的联系人',
  'ChatList.Menu.SwitchTo.Webogram': '切换到旧版本',
  'ChatList.Menu.SwitchTo.A': '切换到 A 版本',
  'ConnectionStatus.ForceReconnect': '立即重新连接',
  'ConnectionStatus.ReconnectInPlain': '%ds 后重新连接',
  'ConnectionStatus.ReconnectIn': '%ds 后重新连接，%s',
  'ConnectionStatus.Reconnect': '重新连接',
  'ConnectionStatus.Reconnecting': '正在重新连接...',
  'ConnectionStatus.TimedOut': '请求超时，%s',
  'ConnectionStatus.Waiting': '等待网络...',
  'Contacts.Count': {
    'one_value': '%d 个联系人',
    'other_value': '%d 个联系人'
  },
  'Deactivated.Title': '标签页过多...',
  'Deactivated.Subtitle': 'Telegram 仅支持一个活动标签页。\n点击任意处继续使用此标签页。',
  'Deactivated.Version.Title': 'WebK 已更新...',
  'Deactivated.Version.Subtitle': '另一个标签页正在运行较新版本的 Telegram。\n点击任意处重新加载此标签页。',
  'General.Keyboard': '键盘',
  'General.SendShortcut.Enter': '按 Enter 发送',
  'General.SendShortcut.CtrlEnter': '按 %s + Enter 发送',
  'General.SendShortcut.NewLine.ShiftEnter': '按 Shift + Enter 换行',
  'General.SendShortcut.NewLine.Enter': '按 Enter 换行',
  'General.TimeFormat': '时间格式',
  'General.TimeFormat.h12': '12 小时制',
  'General.TimeFormat.h23': '24 小时制',
  'ChatBackground.UploadWallpaper': '上传壁纸',
  'ChatBackground.Blur': '模糊壁纸图像',
  'Notifications.Sound': '通知声音',
  'Notifications.Sound.Sent': '消息已发送',
  'Notifications.Sound.Volume': '声音音量',
  'Notifications.Sound.Caption': '拖动并释放或点击以测试音量。',
  'Notifications.Web': 'Web 通知',
  'Notifications.Show': '显示通知',
  'Notifications.Offline': '显示离线通知',
  'Notifications.Sound.Section': '声音',
  'Notifications.Sound.Effects': '音效',
  'Notifications.Default': '授予 Telegram 发送通知的权限。您可能需要刷新页面才能看到更改。',
  'Notifications.Enable': '启用通知',
  'Notifications.Restricted': '您已限制通知。在浏览器中重置权限并重试。',
  'NewPrivateChat': '新建私聊',
  'NewPoll.OptionLabel': '选项 %d',
  'Message.Context.Selection.Copy': '复制选中内容',
  'Message.Context.Selection.Clear': '清除选择',
  'Message.Context.Selection.Delete': '删除选中内容',
  'Message.Context.Selection.Forward': '转发选中内容',
  'Message.Context.Selection.Download': '下载选中内容',
  'Message.Context.Selection.SendNow': '立即发送选中内容',
  'Message.Unsupported.Desktop': '__此消息目前在 Telegram Web 上不受支持。请尝试 [getdesktop.telegram.org](https://getdesktop.telegram.org/)__',
  'Message.Unsupported.Mobile': '__此消息目前在 Telegram Web 上不受支持。请尝试 [telegram.org/dl](https://telegram.org/dl/)__',
  'Checkbox.Enabled': '已启用',
  'Checkbox.Disabled': '已禁用',
  'Error.PreviewSender.CaptionTooLong': '标题过长。',
  'PreviewSender.GroupItems': '群组项目',
  'PreviewSender.SendAlbum': {
    'one_value': '发送相册',
    'other_value': '发送 %d 个相册'
  },
  'Presence.YourChat': '与自己的聊天',
  'Privacy.Devices': {
    'one_value': '%1$d 台设备',
    'other_value': '%1$d 台设备'
  },
  'Privacy.Websites': {
    'one_value': '%1$d 个网站',
    'other_value': '%1$d 个网站'
  },
  'Privacy.SensitiveContent': '敏感内容',
  'Privacy.Bio': '谁可以看到我的个人简介',
  'Privacy.BioCaption': '您可以精确限制谁可以在您的个人资料中看到简介。',
  'PrivacyModal.Search.Placeholder': '添加用户或群组...',
  'Permissions.NoExceptions': '无例外',
  'Permissions.ExceptionsCount': {
    'one_value': '%d 个例外',
    'other_value': '%d 个例外'
  },
  'Permissions.RemoveFromGroup': '您确定要将 **%s** 从群组中移除吗？',
  'PWA.Install': '安装应用',
  'Link.Available': '链接可用',
  'Link.Taken': '链接已被占用',
  'Link.Invalid': '链接无效',
  'Language.zh-CN': '简体中文',
  'Language.zh': '中文',
  'Language.zh-TW': '繁體中文',
  'Language.en': '英语',
  'Language.ru': '俄语',
  'Language.ja': '日语',
  'Language.ko': '韩语',
  'Profile': '个人资料',
  'Saved': '已保存',
  'Deleted': '已删除',
  'ReportBug': '报告错误',
  'LogOut.Description': '您确定要退出登录吗？\n\n请注意，您可以在所有设备上无缝使用 Telegram。',
  'SearchPlaceholder': '搜索...',
  'SelectAll': '全选',
  'SelectAll2': '全选',
  'DeselectAll': '取消全选'
};

export default lang;
