/** https://translations.telegram.org/zh-hans/webk/
let str = `'LanguageName': '中文',\n`
str += `'${key[index].innerText}': '${value[index].innerText}',\n`

lang['LanguageName'] = '中文';
const key = document.querySelectorAll('.tr-value-key')
const value = document.querySelectorAll('.tr-value-suggestions .tr-value')
for (let index = 0; index < key.length; index++) {
  lang[key[index].innerText] = value[index].innerText;
}
 */
const lang = {
  "Login.Title": "登录 Telegram",
  "Login.PhoneLabel": "手机号码",
  "Login.PhoneLabelInvalid": "此手机号码无效",
  "Login.StartText": "请确认您的国际电话区号\n并输入您的手机号码。",
  "Login.Code.SentSms": "我们已向你发送一条带有登录代码的短信。",
  "Login.Code.SentInApp": "我们已通过 Telegram 向你发送包含验证码的消息。",
  "Login.Code.SentCall": "We will call you and dictate\nthe code.",
  "Login.Code.SentEmail": "Please check your email **%s** (don't forget the spam folder) and enter the code we just sent you.",
  "Login.Code.SentUnknown": "Please check everything\nfor a code (type: %s)",
  "Login.Password.Title": "输入你的密码",
  "Login.Password.Subtitle": "你的账户由\n额外密码保护",
  "Login.Register.Subtitle": "请输入您的名字并且添加一张用作头像的图片",
  "PleaseWait": "Please wait...",
  "ForgotPassword": "[Forgot Password?]()",
  "TroubleEmail": "[Can't access this email?]()",
  "Login.ResetPassword.Title": "Reset Password",
  "Login.ResetPassword.Subtitle": "Enter the code we just sent\nto your email **%s**.",
  "Login.ResetPassword.Cancel": "Cancel",
  "Login.ResetPassword.NoEmailText": "Since you didn't provide a recovery email when setting up your password, your remaining options are either to remember your password or to reset your account.",
  "Login.ResetPassword.TroubleEmailText": "If you can't restore access to your email, your remaining options are either to remember your password or to reset your account.",
  "Login.ResetPassword.ResetAccount": "Reset Account",
  "Login.ResetAccount.Title": "Warning",
  "Login.ResetAccount.Text": "This action can't be undone.\n\nIf you reset your account, all your messages and chats will be deleted.",
  "Login.ResetAccountFail.Title": "Sorry",
  "Login.ResetAccountFail.TextCancelled": "Your recent attempts to reset this account have been cancelled by its active user. Please try again in 7 days.",
  "Login.ResetAccountFail.TextWait": "Since this account is active and protected by a password, we will delete it in 1 week for security purposes.\n\nYou can cancel this process at any time.\n\nYou'll be able to reset your account in: %s.",
  "Login.ResetEmail.Title": "Reset Email",
  "Login.ResetEmail.Text": "You can change your login email if you are logged into Telegram from another device.\n\nOtherwise, if you don't have access to this email, you can reset it with an **SMS** code in **%s**.",
  "Login.ResetEmail.Pending": "Email will be reset in %s. [Reset now via SMS]()",
  "Login.ResetEmail.PleaseWait": "Resetting email, please wait...",
  "Login.ResetEmail.NeedPremium": "Telegram Premium Required",
  "Login.ResetEmail.NeedPremiumText": "Due to the high cost of SMS in your country, you need a **Telegram Premium** account to immediately reset this email via an SMS code.\n\nYou can ask a friend to gift a Premium subscription for your account",
  "Login.Passkey": "Log in by passkey",
  "Login.Passkey.Error": "Something went wrong",
  "Login.Passkey.Error.NotFound": "Used passkey is not tied to any account",
  "Code": "验证码",
  "LoginPassword": "Password",
  "YourName": "您的姓名",
  "FirstName": "名字（必填）",
  "LastName": "姓氏（可选）",
  "StartMessaging": "开始聊天",
  "Country": "国家",
  "Contacts.PhoneNumber.Placeholder": "手机号",
  "Login.Next": "下一步",
  "Login.ContinueOnLanguage": "继续用 English",
  "Login.QR.Title": "扫码登录 Telegram",
  "Login.QR.Help1": "在您的手机上打开Telegram",
  "Login.QR.Help2": "请转到**设置** > **设备** > **关联桌面设备**",
  "Login.QR.Help3": "点击手机屏幕确认登录",
  "Login.QR.Cancel": "手机号登录",
  "Login.QR.Login": "扫描二维码登录",
  "PhoneNumber.Code.Fragment.Info": "Get the code in the Numbers section on [Fragment](%1$@)",
  "PHONE_CODE_INVALID": "验证码无效",
  "PHONE_CODE_EXPIRED": "验证码过期",
  "PASSWORD_HASH_INVALID": "密码不正确",
  "LanguageName": "中文",
  "Login.KeepSigned": "保持登录状态",
  "NewGroup": "新建群组",
  "Contacts": "联系人",
  "Saved": "收藏",
  "Settings": "设置",
  "SettingsHelp": "帮助",
  "HistoryCleared": "历史记录已被清空",
  "NewChannel": "新建频道",
  "NewPrivateChat": "新建私聊",
  "MarkAsUnread": "标记为未读",
  "ChatList.Context.Pin": "置顶",
  "ChatList.Context.Mute": "静音",
  "Delete": "删除",
  "MarkAsRead": "标记为已读",
  "ChatList.Context.Unpin": "取消置顶",
  "ChatList.Context.Unmute": "取消静音",
  "Unarchive": "取消归档",
  "Archive": "归档",
  "AttachSticker": "表情",
  "FromYou": "您",
  "AttachRound": "视频消息",
  "Draft": "草稿",
  "AttachAudio": "语音消息",
  "AttachContact": "联系人",
  "AttachLiveLocation": "实时位置信息",
  "AttachGif": "GIF 动态图",
  "AttachVideo": "视频",
  "AttachPhoto": "图片",
  "AttachAlbum": "相册",
  "SharedVoiceTab2": "语音消息",
  "DeleteChatUser": "删除对话",
  "AreYouSureDeleteThisChatWithUser": "您确定要删除与 **%1$s** 的对话吗？",
  "DeleteMessagesOptionAlso": "同时为%1$s删除",
  "LeaveMegaMenu": "退出群组",
  "AreYouSureDeleteAndExitName": "您确定要删除并退出 **%1$s** 群组吗？",
  "Chat.Service.Channel.UpdatedVideo": "频道图片已更新",
  "Suggestion.Notifications": "绝不曾错过任何消息! %s",
  "Suggestion.Notifications.Subtitle": "启用通知以掌握最新动态。",
  "Chat.Service.PeerJoinedTelegram": "%@ 加入了 Telegram",
  "Search.From": "来自：",
  "Search.Member": "搜索成员",
  "Date.Today": "今天",
  "ActionCreateChannel": "频道已创建",
  "Members": "%1$d 位成员",
  "ActionMigrateFromGroup": "此群组已升级为超级群组",
  "Chat.Service.Channel.UpdatedPhoto": "频道头像已更新",
  "Chat.Service.Channel.RemovedPhoto": "频道头像已删除",
  "ActionAddUserSelfYou": "您返回了此群组",
  "Chat.Service.Channel.UpdatedTitle": "频道名称已修改为 \"%@\"",
  "NewPoll": "发起投票",
  "AskAQuestion": "向我们提问",
  "PollOptions": "投票选项",
  "NewPoll.OptionsAddOption": "添加一个选项",
  "NewPoll.Anonymous": "匿名投票",
  "NewPoll.MultipleChoice": "可多选",
  "NewPoll.Quiz": "问答模式",
  "AccDescrQuizExplanation": "注释",
  "NewPoll.Explanation.Placeholder": "添加评论（可选）",
  "AddAnExplanationInfo": "选错的用户将看到这段文字，因此非常适合教育用途。",
  "Chat.Subscribe": "订阅",
  "PinnedMessage": "置顶消息",
  "Comments": "%1$d 条评论",
  "CreateGroup.NameHolder": "群组名称",
  "Channel.DescriptionHolderDescrpiton": "您可以给您的频道添加一段简介。",
  "GroupAddMembers": "添加成员",
  "SendMessageTo": "添加成员…",
  "LinkCopied": "链接已复制到剪贴板",
  "LinkCopiedPrivateInfo": "该链接仅供本群组成员使用",
  "Edit": "编辑",
  "DescriptionPlaceholder": "简介",
  "ChannelType": "频道类型",
  "TypePrivate": "私密",
  "PeerInfo.Discussion": "讨论",
  "PeerInfo.Discussion.Add": "添加",
  "PeerInfo.Administrators": "管理员",
  "PeerInfo.SignMessages": "消息署名",
  "PeerInfo.Subscribers": "订阅者数量",
  "Subscribers": "%1$d 位订阅者",
  "PeerInfo.DeleteChannel": "删除频道",
  "ChannelDeleteMenu": "删除频道",
  "AreYouSureDeleteAndExitChannel": "你确定要删除并离开此频道吗？",
  "DeleteChannelForAll": "为所有订阅者删除",
  "GroupType": "群组类型",
  "TypePrivateGroup": "私人",
  "ChannelPermissions": "权限",
  "GroupMembers": "成员",
  "MegaPrivate": "私密群组",
  "MegaPrivateInfo": "私密群组只能通过群成员的邀请，或邀请链接加入。",
  "MegaPublic": "公开群组",
  "MegaPublicInfo": "任何人都可以搜索、加入公开群组，并查看历史聊天记录。",
  "MegaPrivateLinkHelp": "任何人都可以通过此链接加入您的群组。您可以随时废除此链接。",
  "RevokeLink": "废除链接",
  "DeleteMega": "解散群组",
  "Link.Available": "链接有效",
  "Channel.UsernameAboutGroup": "用户可以分享此链接给他人，并且能通过搜索找到您的群组。",
  "Link.Invalid": "链接无效",
  "ChannelPermissionsHeader": "本群组成员有何权限?",
  "UserRestrictionsSend": "发送消息",
  "UserRestrictionsSendMedia": "发送媒体文件",
  "UserRestrictionsSendStickers": "发送表情和 GIF 动态图",
  "UserRestrictionsSendPolls": "发起投票",
  "UserRestrictionsEmbedLinks": "嵌入链接预览",
  "UserRestrictionsInviteUsers": "添加用户",
  "UserRestrictionsPinMessages": "置顶消息",
  "UserRestrictionsChangeInfo": "修改群组信息",
  "PrivacyExceptions": "例外",
  "ChannelAddException": "添加例外",
  "Permissions.NoExceptions": "无例外",
  "ChannelBlockedUsers": "被移除的用户",
  "NoBlockedUsers": "暂无被移除的用户",
  "UserRestrictions": "用户权限",
  "UserRestrictionsCanDo": "这位用户可以做什么？",
  "UserRestrictionsBlock": "封禁并从群组中移除",
  "RevokeAlert": "您确定要废除此邀请链接吗？一旦废除，其他人将不能通过此链接加入此群组。",
  "RevokeButton": "废除",
  "ExceptionModal.Search.Placeholder": "添加例外...",
  "GroupPermission.Delete": "删除例外",
  "DeleteMegaMenu": "解散群组",
  "AreYouSureDeleteAndExit": "您确定要删除并退出此群组吗？",
  "DeleteChat.DeleteGroupForAll": "为所有成员删除",
  "Peer.Status.Member": "%d 位成员",
  "Peer.Status.Subscribers": "%d 个订阅者",
  "ActionCreateGroup": "un1 创建了该群组",
  "ActionLeftUser": "un1 退出了群组",
  "ActionAddUserSelf": "un1 返回了此群组",
  "ActionPinnedNoText": "un1 置顶了一条消息",
  "ActionRemovedPhoto": "un1 移除了群组头像",
  "ActionChangedVideo": "un1 已更改群组图片",
  "ActionAddUser": "un1 添加了 un2",
  "ActionKickUser": "un1 移除了 un2",
  "ActionChangedTitle": "un1 将群组名称更改为 un2",
  "ActionInviteUser": "un1 通过邀请链接加入了此群组",
  "ActionChangedPhoto": "un1 更换了群组头像",
  "EditAccount.Username": "用户名",
  "Telegram.NotificationSettingsViewController": "通知",
  "Checkbox.Disabled": "已停用",
  "SharedMediaTab2": "媒体",
  "SharedFilesTab2": "文件",
  "SharedLinksTab2": "链接",
  "SharedMusicTab2": "音频",
  "PhoneCopied": "已复制手机号码到剪贴板",
  "UsernameCopied": "用户名已复制到粘贴板",
  "BioCopied": "个人简介已复制至剪贴板。",
  "UserBio": "个人简介",
  "Username": "用户名",
  "Phone": "手机号码",
  "Notifications": "通知",
  "DeleteContact": "删除联系人信息",
  "AreYouSureDeleteContact": "您确定要删除此联系人吗？",
  "EditContact.OriginalName": "原来的名字",
  "EditProfile.FirstNameLabel": "名字",
  "Login.Register.LastName.Placeholder": "姓氏",
  "Checkbox.Enabled": "已启用",
  "PeerInfo.DeleteContact": "删除联系人",
  "Profile": "个人资料",
  "Lately": "最近曾上线",
  "AnonymousNumber": "匿名号码",
  "LastSeenTitle": "谁可以看到您最后上线的时间？",
  "PrivacyProfilePhotoTitle": "谁能看见我的头像？",
  "PrivacySettingsController.LastSeenDescription": "注意：如果对方没有和你分享他们的最近在线时间，则你只能看到大致的时间段，如最近，一周内，一个月内等。",
  "RecentSessions.Error.FreshReset": "出于安全原因，您无法终止刚刚连接的设备上的会话。 请使用之前的设备连接或等待几个小时。",
  "AreYouSureSessionTitle": "结束会话",
  "Terminate": "结束",
  "EditAccount.Title": "编辑个人资料",
  "Bio.Description": "您可以在此输入任何有关您个人的信息，诸如：年龄、工作或居住城市。\n示例：23岁，来自旧金山的设计师。",
  "EditProfile.Username.Invalid": "用户名无效",
  "EditProfile.Username.Taken": "用户名已存在",
  "FilterNew": "新文件夹",
  "FilterIncludeExcludeInfo": "请选择将出现或永远不出现在该文件夹中的聊天和聊天类型。",
  "FilterInclude": "包含的聊天",
  "ChatList.Filter.Include.AddChat": "所有对话",
  "FilterExclude": "排除的聊天",
  "ChatList.Filter.Exclude.AddChat": "添加对话",
  "AutoplayGIF": "GIF 动态图 ",
  "AutoplayVideo": "视频",
  "Telegram.InstalledStickerPacksController": "表情",
  "Stickers.SuggestStickers": "根据 Emoji 联想表情",
  "InstalledStickers.LoopAnimated": "循环播放动态贴纸",
  "FilterAlwaysShow": "包含聊天",
  "FilterChatTypes": "聊天类型",
  "ChatList.Filter.Contacts": "联系人",
  "ChatList.Filter.NonContacts": "非联系人",
  "ChatList.Filter.Groups": "群组",
  "ChatList.Filter.Channels": "频道",
  "ChatList.Filter.Bots": "机器人",
  "FilterChats": "聊天",
  "FilterNeverShow": "排除聊天",
  "ChatList.Filter.MutedChats": "已静音",
  "ChatList.Filter.Archive": "归档",
  "ChatList.Filter.ReadChats": "已读",
  "NotificationsPrivateChats": "私聊",
  "NotificationsForPrivateChats": "私聊通知",
  "NotificationsGroups": "群组",
  "NotificationsForGroups": "群组通知",
  "NotificationsChannels": "频道",
  "NotificationsForChannels": "频道通知",
  "NotificationsOther": "其它",
  "ContactJoined": "联系人已加入 Telegram",
  "Notifications.Sound": "通知音",
  "UsernameHelpLink": "通过此链接可以与您进行对话：\n%1$s",
  "Filters": "文件夹",
  "Chats": "%1$d 个对话",
  "Channels": "%1$d个频道",
  "Groups": "%1$d个群组",
  "PrivacyPhone": "手机号码",
  "PrivacyPhoneTitle": "谁可以看见我的手机号码？",
  "PrivacySettingsController.Everbody": "所有人",
  "PrivacySettingsController.MyContacts": "我的联系人",
  "PrivacySettingsController.Nobody": "不允许任何人",
  "PrivacyPhoneInfo": "已将您的手机号码保存到联系人的用户也将在 Telegram 上看到它。",
  "PrivacySettingsController.NeverShare": "从不分享给",
  "Users": "%1$d 位用户",
  "PrivacySettingsController.AlwaysShare": "总是分享给",
  "PrivacySettingsController.AddUsers": "添加用户",
  "PrivacySettingsController.PeerInfo": "这些设定会覆盖上面的设定。",
  "EditProfile.BioLabel": "个人简介（可选）",
  "EditProfile.Username.Label": "用户名（可选）",
  "PrivacyPhoneTitle2": "谁可以通过手机号码找到我？",
  "PrivacyPhoneInfo3": "只有添加你的手机号码到自己联系人列表中的人才可以在Telegram上查看您的联系人信息。",
  "ChatList.Filter.List.Title": "聊天文件夹",
  "ChatList.Filter.Header": "为不同组别的聊天建立分组以快速切换聊天。",
  "ChatList.Filter.NewTitle": "创建文件夹",
  "FilterRecommended": "推荐的文件夹",
  "SessionsTitle": "活跃会话",
  "CurrentSession": "此设备",
  "TerminateSessionText": "您确定要结束此会话吗？",
  "Cancel": "取消",
  "PrivacySettings.VoiceCalls": "语音通话",
  "WhoCanCallMe": "谁可以给我打电话？",
  "PrivacySettingsController.PhoneCallDescription": "你可以限制其他人和你语音通话的权限",
  "PrivacyP2PHeader": "端对端",
  "PrivacySettingsController.P2p.Desc": "禁用端对端连接后，所有通话流量将使用 Telegram 服务器中转以避免泄露您的 IP 地址，但可能会轻微降低音质。",
  "AreYouSureSessionsTitle": "结束会话",
  "AreYouSureSessions": "您确定要注销所有其它设备上的会话吗？",
  "TerminateAllSessions": "注销所有其它设备上的会话",
  "OtherSessions": "活跃会话",
  "EditAccount.Logout": "注销",
  "AccountSettings.Filters": "聊天文件夹",
  "Telegram.GeneralSettingsViewController": "通用设置",
  "AccountSettings.Notifications": "通知",
  "AccountSettings.PrivacyAndSecurity": "隐私和安全",
  "AccountSettings.Language": "语言",
  "EditProfile.Username.Available": "用户名可用",
  "PrivacySettings.Forwards": "转发的消息",
  "PrivacyForwardsTitle": "转发我的消息时，谁可以链接至我的账号？",
  "PrivacySettingsController.Forwards.CustomHelp": "你可以选择所传的消息被其他用户转发时，是否可以链接回你的帐号。",
  "PrivacySettingsController.AlwaysAllow": "总是允许",
  "PrivacyAndSecurity.Item.On": "开启",
  "FilterHeaderEdit": "编辑文件夹",
  "FilterMenuDelete": "删除文件夹",
  "FilterAllContacts": "所有联系人",
  "FilterAllNonContacts": "所有非联系人",
  "FilterAllGroups": "所有群组",
  "FilterAllChannels": "所有频道",
  "FilterAllBots": "所有机器人",
  "Add": "添加",
  "BlockedUsers": "已拉黑用户",
  "BlockModal.Search.Placeholder": "屏蔽用户...",
  "PrivacyModal.Search.Placeholder": "添加用户或群组...",
  "FilterShowMoreChats": "显示其他  %1$d 个聊天",
  "TwoStepAuth.SetupHintTitle": "密码提示",
  "TwoStepAuth.SetupHintPlaceholder": "提示",
  "Continue": "继续",
  "YourEmailSkip": "跳过",
  "YourEmailSkipWarning": "警告",
  "YourEmailSkipWarningText": "您确定不设置密码恢复邮箱吗？\n\n一旦您忘记了密码，您将无法再访问您的 Telegram 帐号，并且再也没有办法恢复帐号数据。",
  "TwoStepAuth.RecoveryTitle": "电子邮箱验证码",
  "TwoStepAuth.ConfirmEmailCodeDesc": "请输入我们刚刚发送到 %@ 的验证码",
  "TwoStepAuth.RecoveryCode": "验证码",
  "TwoStepAuth.EmailCodeChangeEmail": "更改电子邮件",
  "ResendCode": "重新发送验证码",
  "TwoStepAuth.RecoveryCodeInvalid": "验证码无效，请重试。",
  "PasswordAsHintError": "密码提示必须与密码本身不同",
  "TwoStepVerificationPasswordSet": "密码已设置！",
  "TwoStepVerificationPasswordSetInfo": "在新设备上登录时除了短信验证码还需要输入此两步验证密码。",
  "TwoStepVerificationPasswordReturnSettings": "跳转到设置",
  "TwoStepVerificationTitle": "两步验证",
  "TwoStepAuth.GenericHelp": "您已启用两步验证。\n您将需要此处设置的密码以登录到您的 Telegram 帐号。",
  "TwoStepAuth.ChangePassword": "更改密码",
  "TwoStepAuth.RemovePassword": "停用密码",
  "TwoStepAuth.ChangeEmail": "更改密码恢复电子邮箱",
  "PrivacySettings": "隐私和安全",
  "BlockedEmpty": "无",
  "TwoStepVerification": "两步验证",
  "PrivacyAndSecurity.Item.Off": "关闭",
  "Privacy.Devices": "%1$d 个设备",
  "PrivacyTitle": "隐私",
  "WhoCanAddMe": "谁可以邀请我？",
  "PrivacyProfilePhoto": "头像",
  "PrivacySettingsController.ProfilePhoto.CustomHelp": "您可以精确地限制某些用户查看你的头像。",
  "PrivacyLastSeen": "最后上线时间",
  "BlockedUsersInfo": "被您屏蔽的用户将无法向您发送消息，或邀请您加入群组。该用户也无法看到您的头像、动态、在线状态及最后上线时间。",
  "Unblock": "取消屏蔽",
  "General": "常规",
  "TextSize": "消息字号",
  "ChatBackground": "聊天壁纸",
  "EnableAnimations": "启用动画效果",
  "General.Keyboard": "键盘",
  "General.SendShortcut.Enter": "以 Enter 键发送",
  "General.SendShortcut.NewLine.ShiftEnter": "以 Shift + Enter 键创建换行",
  "General.SendShortcut.CtrlEnter": "以 %s+Enter 键发送",
  "General.SendShortcut.NewLine.Enter": "按 Enter 键换行",
  "AutoDownloadMedia": "自动下载媒体文件",
  "AutodownloadContacts": "联系人",
  "AutodownloadPrivateChats": "私聊",
  "AutodownloadGroupChats": "群聊",
  "AutodownloadChannels": "频道",
  "ChatBackground.UploadWallpaper": "上传壁纸",
  "ChatBackground.Blur": "模糊化背景图片",
  "PrivacySettings.Groups": "群组",
  "PrivacySettingsController.GroupDescription": "您可以限制其他人将您添加到群组或频道的权限",
  "PrivacySettingsController.NeverAllow": "永不允许",
  "PrivacySettingsController.UserCount": "%d 位用户",
  "StickersBotInfo": "艺术家们可以自由地使用机器人 @stickers 创建自己的贴纸包。",
  "StorySavedTitle": "已将 %d 条动态保存至您的个人资料页。",
  "StoryPinnedToProfile": "动态已保存到您的个人资料页。",
  "Story.AddToProfile": "发布至个人资料页",
  "MyStories.Subtitle": "只有您才能够查看归档中的动态，除非你选择将它们发布到您的个人资料页中。",
  "NoStoryFound": "抱歉，这条动态似乎不存在。",
  "OpenStory": "打开动态",
  "StoryJustNow": "刚刚",
  "StoryMentionView": "查看动态",
  "StoriesCount": "%1$d 条动态",
  "PublicStories": "公开动态",
  "Stories": "动态",
  "StoryViewLocation": "查看位置",
  "Story.ReportTitle": "举报动态",
  "Story.ExpiredToast": "此动态已无法访问",
  "Story.NoSound": "这段视频没有声音",
  "Story.RemoveFromProfile": "从个人资料页移除",
  "Story.ReplyPlaceholder": "私信回复…",
  "ExpiredStoryMentionYou": "您提到 %s 的动态已无法访问",
  "YourStory": "您的动态",
  "StoryMention": "%s 在动态中提到了您",
  "StoryMentionYou": "您在动态中提到了 %s",
  "StoryCantReply": "您无法回复此动态",
  "MyStories.Title": "我的动态",
  "ExpiredStorySubtitle": "来自：%s",
  "ExpiredStory": "过期的动态",
  "ForwardedStoryFrom": "转发的动态\n来自：%s",
  "ArchivedStories": "已归档的动态",
  "SavedStories": "已发布的动态",
  "UnarchiveStories": "取消隐藏动态",
  "ArchivePeerStories": "隐藏动态",
  "NotificationsStoryUnmute2": "接收\n动态通知",
  "NotificationsStoryMute2": "不接收动态通知",
  "NobodyViewsArchived": "没有可用的查看记录",
  "StoryContactsHint": "只有 **%s** 的联系人可以查看此动态。",
  "StoryCloseFriendsHint": "您能看到这条动态是因为 **%s** 将您添加到了密友列表中。",
  "DeleteStoriesSubtitle": "您确定要删除 %d 条动态吗？",
  "DeleteStorySubtitle": "您确定想要删除此动态吗？",
  "DeleteStoriesTitle": "删除动态",
  "DeleteStoryTitle": "删除动态",
  "StoryArchived": "已从您的个人资料页移除 %d 条动态",
  "StoryArchivedFromProfile": "此动态已从您的个人资料页隐藏。",
  "Chat.Input.Attach.PhotoOrVideo": "图片或视频",
  "Chat.Input.Attach.Document": "文档",
  "PreviewSender.SendAlbum": "发送 %d 个相册",
  "PreviewSender.GroupItems": "捆绑项目",
  "PreviewSender.CaptionPlaceholder": "添加说明...",
  "PreviewSender.SendFile": "发送 %d 个文件",
  "Caption": "说明",
  "PreviewSender.SendPhoto": "发送 %d 张照片",
  "Error.PreviewSender.CaptionTooLong": "说明文字太长了。",
  "PreviewSender.SendVideo": "发送 %d 个视频",
  "StickersTab.SearchPlaceholder": "查找贴纸",
  "Stickers.SearchAdded": "已添加",
  "Stickers.SearchAdd": "添加",
  "Error.RequestPeer.NoRights.Group": "抱歉，您无法将机器人添加到本群组中。",
  "Chat.Service.BotPermissionAllowed": "您允许该机器人在您使用 %@ 登录时向您发出消息。",
  "BotWebViewCloseAnyway": "仍然关闭",
  "Alert.BotAppDoesntExist": "抱歉，该应用不存在。",
  "WebApp.WriteAccess.Title": "允许发送消息",
  "WebApp.WriteAccess.Description": "允许 %s 发送消息？",
  "ActionBotAllowedRequest": "您允许此机器人在接受请求时向您发送消息。",
  "UsernameActivateLinkBotMessage": "您想要在机器人的信息页面上显示此链接吗？",
  "Error.RequestPeer.NoRights.Channel": "抱歉，您无法将机器人添加到本频道中。",
  "EditBot.Title": "编辑机器人",
  "UsernamesBotHelp": "拖拽以调整机器人信息页中链接显示的顺序。",
  "EditBot.Buttons.Settings": "更改机器人设置",
  "EditBot.Buttons.Commands": "修改命令",
  "EditBot.Buttons.Intro": "修改简介",
  "Checkout.PasswordEntry.Pay": "支付",
  "PaymentCheckoutName": "姓名",
  "PrivacyClearPayment": "付款信息",
  "PrivacyPaymentsPaymentShippingCleared": "支付与配送信息已清空。",
  "PrivacyPaymentsPaymentInfoCleared": "支付信息已清除。",
  "PrivacyPaymentsClearAlertText": "您确定要清除付款和物流信息吗？",
  "PrivacyPaymentsClearAlertTitle": "清除付款信息",
  "PrivacyPaymentsClear": "清除付款和配送信息",
  "PrivacyPayments": "付款",
  "PaymentShippingSaveInfo": "您可以保存您的配送信息以便在未来使用。",
  "PaymentCheckoutPhoneNumber": "手机号码",
  "PaymentShippingEmailPlaceholder": "电子邮箱",
  "PaymentCardSavePaymentInformation": "保存付款信息",
  "PaymentTransactionTotal": "总计",
  "PaymentCheckout": "结算",
  "PaymentCard.Error.Invalid": "卡号无效",
  "PaymentInfo.Billing.Title": "输入你的付款地址",
  "PaymentInfo.CVV": "安全码（CVV）",
  "ChatList.Service.Call.Cancelled": "取消的电话",
  "SavedMessages": "我的收藏",
  "ArchivedChats": "已归档对话",
  "Chat.Date.ScheduledForToday": "今日日程",
  "Chat.Date.ScheduledFor": "计划于 %@发送",
  "Loading": "加载中…",
  "Search": "搜索",
  "Chat.Menu.SelectMessages": "选择消息",
  "Chat.Menu.ClearSelection": "清除所选",
  "Forward": "转发",
  "Reply": "回复",
  "Message.Context.Pin": "置顶",
  "Message.Context.Select": "选择",
  "PinnedMessagesCount": "%1$d 条置顶消息",
  "Chat.Pinned.DontShow": "不显示置顶消息",
  "Message.Context.Unpin": "取消置顶",
  "ShareModal.Search.ForwardPlaceholder": "转发到…",
  "Chat.Send.WithoutSound": "静默发送",
  "Chat.Send.ScheduledMessage": "定时消息",
  "Chat.Send.SetReminder": "新建提醒事项",
  "CopyLink": "复制链接",
  "Chat.Poll.Unvote": "撤回投票",
  "Chat.Poll.Stop": "停止投票",
  "JumpToDate": "跳转到此日期",
  "Poll": "投票",
  "Chat.Input.UnpinAll": "取消置顶所有消息",
  "Copy": "复制",
  "Chat.CopySelectedText": "复制所选内容",
  "ScheduledMessages": "定时消息",
  "Reminders": "提醒",
  "Chat.Selection.LimitToast": "已达到最大可选数量。",
  "Message.Context.Selection.Forward": "转发所选",
  "Message.Context.Selection.Clear": "清除所选",
  "Message.Context.Selection.Delete": "删除所选",
  "NewPoll.OptionLabel": "选项 %d",
  "Presence.YourChat": "与您自己的对话",
  "LastSeen.HoursAgo": "最近上线于 %d 小时前",
  "Peer.Status.justNow": "上线于不久前",
  "Peer.ServiceNotifications": "服务通知",
  "Message.Context.Selection.SendNow": "现在发送选中的消息",
  "Message": "消息",
  "Message.Context.Selection.Copy": "复制所选",
  "ChatList.Service.Call.outgoing": "播出通话 (%@)",
  "ChatList.Service.Call.Missed": "未接电话",
  "ChatList.Service.Call.incoming": "来电 (%@)",
  "MultiAccount.AddAccount": "添加账户",
};

export default lang;
